### ISSUE TITLE
400: Invalid label name - invalidArgument

### ISSUE THREAD

**Issue by NinjaXYZ** [GAM-team/got-your-back#390] opened 2022-07-19 20:33 UTC
The issue tracker is for reporting product deficiencies. How do I questions should be posted to the discussion forum at https://groups.google.com/group/got-your-back. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GYB release from https://github.com/jay0lee/got-your-back/releases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/got-your-back/wiki

Full steps to reproduce the issue:
1. 
2.
3.

Expected outcome (what are you trying to do?):

Actual outcome (what errors or bad behavior do you see instead?):

**Comment by NinjaXYZ** [comment] 2022-07-19 20:34
400: Invalid label name - invalidArgument 
How do I fix this...

**Comment by NinjaXYZ** [comment] 2022-07-19 20:35
> 400: Invalid label name - invalidArgument
Command:
gyb --email NEWusername@csps.com  --action restore --local-folder "c:\gyb\LastNameFirstIntial" --service-account

**Comment by krystof-k** [comment] 2022-08-19 11:53
Probably a duplicate of #392.

**Comment by NinjaXYZ** [comment] 2022-08-30 19:05
What is the command to estimate labels

**Closed** 2022-08-30 19:07 UTC

**Comment by NinjaXYZ** [comment] 2022-08-30 19:09
This is closed?

**Comment by NinjaXYZ** [comment] 2022-08-30 19:10
I just need the command to see the estimation for a
 label
