### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character '\U0001d000' in position 28781: ordinal not in range(128)

### ISSUE THREAD

**Issue by jsight** [GAM-team/got-your-back#325] opened 2021-09-08 17:38 UTC
The issue tracker is for reporting product deficiencies. How do I questions should be posted to the discussion forum at https://groups.google.com/group/got-your-back. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GYB release from https://github.com/jay0lee/got-your-back/releases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/got-your-back/wiki

Full steps to reproduce the issue:
1.  /home/jsight/bin/gyb/gyb --email <myemail> --local-folder /home/jsight/backup/gmail/gotyourback/jessesightler_gmailcom/

Expected outcome (what are you trying to do?):
Backup completion

Actual outcome (what errors or bad behavior do you see instead?):

Traceback (most recent call last):                                              
  File "gyb.py", line 2429, in <module>
  File "gyb.py", line 1814, in main
  File "gyb.py", line 712, in callGAPI
  File "googleapiclient/_helpers.py", line 134, in positional_wrapper
  File "googleapiclient/http.py", line 1593, in execute
  File "googleapiclient/model.py", line 220, in response
  File "googleapiclient/model.py", line 282, in deserialize
  File "json/__init__.py", line 346, in loads
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Invalid control character at: line 7 column 112929 (char 113019)
[762267] Failed to execute script gyb

**Comment by Hello1024** [comment] 2021-11-19 13:44
Does this error happen repeatedly, or was it a one-off occurrence?   If one-off, it looks like the fault might be on googles end.

It seems real unlikely for a JSON error to happen so far into the response using googles official client...

Do you have some kind of "Web firewall" proxy software which is perhaps trying to meddle with the connection between gyb and google?

**Comment by jay0lee** [comment] 2022-01-22 15:44
Closing due to lack of detail and reproducibility. Feel free to re-open with more details.

**Closed by jay0lee** 2022-01-22 15:44 UTC

**Comment by zegor-mjol** [comment] 2022-02-23 05:29
It happened to me just now. A (large) GMail account was backed up, by GYB, and then to be restored under a different account. 
The error message is
Traceback (most recent call last):15404)                                        
  File "gyb.py", line 2532, in <module>
  File "gyb.py", line 2007, in main
  File "gyb.py", line 1781, in message_hygiene
  File "email/message.py", line 178, in as_bytes
  File "email/generator.py", line 116, in flatten
  File "email/generator.py", line 181, in _write
  File "email/generator.py", line 218, in _dispatch
  File "email/generator.py", line 268, in _handle_multipart
  File "email/generator.py", line 410, in write
UnicodeEncodeError: 'ascii' codec can't encode character '\ufffd' in position 5688: ordinal not in range(128)
[9100] Failed to execute script 'gyb' due to unhandled exception!

**Comment by jay0lee** [comment] 2022-02-23 08:13
What command were you using?
